<div class="cbf_case">
	<div class="cbf_title">¿Cómo funciona?</div>
    <div class="cbf_content" style="height:281px;">
    	<p>Ingresa tus datos y haz click en "Solicitar Reserva".</p>
        <p>En menos de 30 minutos* recibirás un e-mail con la respuesta a tu solicitud.</p>
    </div>
    <div class="cbf_message">
    	*Solicitudes realizadas después de las 10:00pm (22:00) serán respondidas al día siguiente antes de las 09:00am.
    </div>
</div>

<div class="cbf_case">
	<div class="cbf_title">Solicitud Reserva</div>
     <div class="cbf_content">
    	<p><i>Detalles</i></p>
        <p><h3><?php echo $this->branch['company']; ?></h3><span class="address"><?php echo $this->branch['bra_address']; ?></span></p>
        <p class="money">$<?php echo number_format($this->branch['fie_sch_value'],0,",","."); ?></p>
        <p>
        	<span class="cbf_info">Fecha: <?php echo substr($this->branch['fie_sch_date'],0,10); ?></span>
            <span class="cbf_info">Hora: <?php echo substr($this->branch['fie_sch_hour'],0,5); ?></span>
            <span class="cbf_info">Tipo de cancha: <?php echo $this->branch['field_kind']; ?></span>
        </p>
    </div>
</div>

<div class="cbf_case">
	<div class="cbf_title_selected">Ingresa tus datos</div>
    <div class="cbf_form">
    	<form name="confirm_booking" id="save_booking" action="#">
        	<fieldset>
                <input type="hidden" name="fields_id" value="<?php echo $this->branch['fie_id']; ?>" />
                <input type="hidden" name="sch_id" value="<?php echo $this->branch['id_fie_sch']; ?>" />
                <input type="hidden" name="sch_date" value="<?php echo $this->branch['fie_sch_date']; ?>" />
                <input type="hidden" name="sch_hour" value="<?php echo $this->branch['fie_sch_hour']; ?>" />
                <p>
                    <span class="field_name">Nombre</span>
                    <span class="error" id="name_error"></span>
                    <input type="text" name="name" id="cbf_name" value="<?php echo App_User::getName(); ?>" placeholder="Nombres" />
                </p>
                <p>
                    <span class="field_name">Apellido</span>
                    <span class="error" id="lastname_error"></span>
                    <input type="text" name="lastname" id="cbf_lastname" value="<?php echo App_User::getLastName(); ?>" placeholder="Apellidos" />
                </p>
                <p>
                    <span class="field_name">CC ó TI</span>
                    <span class="error" id="document_error"></span>
                    <input type="text" name="document" id="cbf_document" placeholder="# Cédula ó Tarjeta de identidad" />
                </p>
                <p>
                    <span class="field_name">E-mail</span>
                    <span class="error" id="email_error"></span>
                    <input type="text" name="email" id="cbf_email" value="<?php echo App_User::getAttrib('use_email'); ?>" placeholder="E-mail" />
                </p>
                <p>
                    <span class="field_name">Teléfono móvil ó fijo</span>
                    <span class="error" id="phone_error"></span>
                    <input type="text" name="phone" id="cbf_phone" placeholder="Teléfono móvil ó fijo" />
                </p>
                <div class="cbf_form_bottom">
                    <a href="#" class="btn_solicitar_256x50"></a>
                </div>
        	</fieldset>
        </form>
    </div>
</div>




<style>
	.cbf_case{
		height:450px;
		width:303px;
		float:left;
		border-right:#ccc 1px solid;
		margin:0; padding:0;
		font-weight:lighter;
	}
	.cbf_case .cbf_title{
		background:#f3f3f0;
		border-top:#f3f3f0 10px solid;
		border-bottom:#CCC 1px solid;
		padding:18px 10px 23px 10px;
		margin:0;
		font-size:24px;
	}
	.cbf_case .cbf_title_selected{
		background:#f3f3f0;
		border-top:#fc9f25 10px solid;
		border-bottom:#CCC 1px solid;
		padding:18px 10px 23px 10px;
		font-size:24px;
	}
	.cbf_case .cbf_content{
		display:table-cell;
		vertical-align:middle;
		padding:35px;
		text-align:left;
		font-size:18px;
		color:#333;
	}
	.cbf_case .cbf_content p{
		margin-bottom:15px;
	}
	.cbf_case .cbf_content i{
		text-decoration:underline;
		font-style:normal;
	}
	.cbf_case .cbf_content h3{
		font-weight:bold;
		font-size:26px;
	}
	.cbf_case .cbf_content .address{
		font-size:14px;
	}
	.cbf_case .cbf_content .money{
		font-weight:bold;
		font-size:36px;
	}
	.cbf_case .cbf_content .cbf_info{
		display:block;
		font-size:14px;
		font-weight:bold;
		margin-bottom:5px;
	}
	.cbf_case .cbf_message{
		border-top:#CCC 1px solid;
		background:#f3f3f0;
		color:#333;
		text-align:left;
		padding:20px;
		font-size:12px;
	}
	
	.cbf_case .cbf_form{
		background:#f3f3f0;
		height:350px;
		color:#333;
		text-align:left;
		padding:20px 35px 0 35px;
	}
	.cbf_case .cbf_form p{
		margin-bottom:10px;
	}
	.cbf_case .cbf_form .field_name{
		font-size:13px;
		padding:0; margin:0;
		color:#222;
	}
	.cbf_case .cbf_form .error{
		font-size:10px;
		color:#F00;
		padding:0; margin:0;
	}
	.cbf_case .cbf_form input{
		border: 1px solid #FFFFFF;
		border-radius: 5px 5px 5px 5px;
		box-shadow: 0 0 2px #000000 inset;
		margin: 0;
		padding: 5px 13px;
		width: 235px;
	}
	.cbf_case .cbf_form .error_input{
		border: 1px solid #F00;
	}
	.cbf_case .cbf_form .cbf_form_bottom{
		position:absolute;
		left:-10px; bottom:-70px;
		vertical-align:center;
	}
	
	.cbf_case input::-webkit-input-placeholder {
    color:#ccc;
	font-weight:lighter;
	}
	.cbf_case input:-moz-placeholder {
		color:    #ccc;
		font-weight:lighter;
	}
</style>

<script>


	$(function(){
		
		$('.btn_solicitar_256x50').click(function(event){
			errors = 0;
			if ($.trim($('#cbf_name').val()) == '') {
				$('#name_error').html('Ingrese su nombre');
				$('#cbf_name').addClass('error_input');
				errors++;
			}else{
				$('#cbf_name').removeClass('error_input');
				$('#name_error').html('');
			}
			if ($.trim($('#cbf_lastname').val()) == '') {
				$('#lastname_error').html('Ingrese su apellido');
				$('#cbf_lastname').addClass('error_input');
				errors++;
			}else{
				$('#cbf_lastname').removeClass('error_input');
				$('#lastname_error').html('');
			}
			if ($.trim($('#cbf_document').val()) == '') {
				$('#document_error').html('Ingrese su documento');
				$('#cbf_document').addClass('error_input');
				errors++;
			}else{
				$('#cbf_document').removeClass('error_input');
				$('#document_error').html('');
			}
			if (!validateEmail($.trim($('#cbf_email').val()))) {
				$('#email_error').html('Ingrese su e-mail valido');
				$('#cbf_email').addClass('error_input');
				errors++;
			}else{
				$('#cbf_email').removeClass('error_input');
				$('#email_error').html('');
			}
			if ($.trim($('#cbf_phone').val()) == '') {
				$('#phone_error').html('Ingrese un número telefónico');
				$('#cbf_phone').addClass('error_input');
				errors++;
			}else{
				$('#cbf_phone').removeClass('error_input');
				$('#phone_error').html('');
			}
			
			if (errors == 0) {				
				$("#confirm_booking").append('<div style="position:absolute; top:0; bottom:0; right:0;  width:304px; background:#fff; filter:alpha(opacity=80); -moz-opacity:0.8; -khtml-opacity: 0.8; opacity: 0.8; z-index:10000; padding:200px 0 0 0; height:250px;" align="center"><img src="/img/loader_32x32.gif" /></div>');
				$.ajax({
					type: "POST",
					url: '/ground/branch/save-booking-form',
					data: $("#save_booking").serialize(), // serializes the form's elements.
					success: function(data)
					{
						$("#confirm_booking").html(data);
					}
				}); 			
			}
			
		});
		
		
		
	});




</script>