<div class="slider_top">
	<div class="squadrapp_canvas">
		<div class="slider_text">
			<h1>Nunca fue tan f&aacute;cil ponerse de acuerdo</h1>
            <h4>Encuentra la cancha de fútbol y convoca a tus amigos para jugar</h4>
		</div>
        <div class="who_in"><div class="fb-facepile" data-app-id="518581128197028" data-max-rows="1" data-size="small" data-width="500" data-colorscheme="dark"></div></div>
        <div class="filtro_canchas_1">
        		<span class="field_name" id="city_label">Ciudad</span>
            	<input type="text" class="city_field" name="city" id="form_city" value="Bogotá" placeholder="¿En qué ciudad quieres jugar?" />
                <input type="hidden" id="form_city_id" value="0" />
                <span class="field_name" id="sport_label">Deporte</span>
                <input type="text" class="sport_field" name="sport" id="form_sport" value="Fútbol" placeholder="Deporte" />
                <input type="hidden" id="form_sport_id" value="0" />
                <span style="padding-top:20px; position:absolute; top:-20px; right:-190px;"><a href="javascript:void(0);" id="send_search" class="btn_search_186x59" onClick="_gaq.push (['_trackEvent' ,'Buscar' ,'clicBoton' ,'Boton_Home']);" ></a></span>
        </div>
	</div>
    <div class="bg_slider">
    	<ul class="bxslider">
        	<li>
            	<div class="bg_slider_bg" style="background:url(<?php echo $this->baseUrl("/images/ground/banner_home_city.jpg"); ?>) top center no-repeat"></div>
            </li>
            <li>
            	<div class="bg_slider_bg" style="background:url(<?php echo $this->baseUrl("/images/ground/banner-home_zoccer_plaza.jpg"); ?>) top center no-repeat"></div>
            </li>
        </ul>
    </div>
</div>
<div class="squadrapp_canvas">
	<div class="subhead">
    <a href="/site/site/registro-cancha" target="_blank" onClick="_gaq.push (['_trackEvent' ,'CentroDeportivo' ,'goRegistro' ,'link_busqueda']);">¿Eres un centro deportivo?, Ingresa aqu&iacute;!</a>
    </div>
</div>
<div class="list_fields" id="search_results">



<div class="message">
	<div>
        	<img src="/img/icon_map_grey.png" />
    </div>
    <div class="message_content">Encuentra la cancha para jugar</div>
</div>



</div>




<style>
	.message{
		text-align:center;
		margin:70px 0;
		color:#9a9a9a;
	}
	.message .message_content{
		font-size:36px;
		font-weight:lighter;
		margin:10px 0 5px 0;
	}
	.message .submessage{
		font-size:24px;
		font-weight:lighter;
	}
	
	.filtro_canchas_1 .field_name{
		position:absolute;
		padding:2px 0;
		font-size:12px;
		color:#DDD;
	}

</style>




<script type="text/javascript">
$(function() {
	
	/**
	**	Carga al iniciar
	**/
	$("#search_results").load("/ground/all/search-fields", {
			   city_id: $("#form_city_id").val(), 
			   sport_id: $("#form_sport_id").val(),
			   city: $("#form_city").val(), 
			   sport: $("#form_sport").val() 
		   }
	);
    
    //autocomplete
    $(".city_field").autocomplete({
        source: "/ground/all/auto-complete-city",
        minLength: 0,
        select: function (event, ui) {
            if(ui.item) {
                $("#form_city").val(ui.item.Name);
                $("#form_city_id").val(ui.item.ID);
            }else{
                $("#form_city_id").val(0);
            }
			$('#form_city').removeClass('error_input');
        }
    }).focus(function() {
			$(this).autocomplete("search", $("#form_city").val());
		});
    $(".sport_field").autocomplete({
        source: "/ground/all/auto-complete-sport",
        minLength: 0,
        select: function (event, ui) {
            if(ui.item) {
                $("#form_sport").val(ui.item.spo_name);
                $("#form_sport_id").val(ui.item.id_spo);
            }else{
                $("#form_sport_id").val(0);
            }
			$('#form_sport').removeClass('error_input');
        }
    }).focus(function() {
			$(this).autocomplete("search", $("#form_sport").val());
		});

    
    $("#send_search").click(function() {
		var errors = 0;
		if ($.trim($('#form_city').val()) == '') {
			$('#form_city').addClass('error_input');
			errors++;
		}else{
				$('#form_city').removeClass('error_input');
			}
		if ($.trim($('#form_sport').val()) == '') {
			$('#form_sport').addClass('error_input');
			errors++;
		}else{
				$('#form_sport').removeClass('error_input');
			}
		if (errors == 0){
		   $("#search_results").load("/ground/all/search-fields", {
			   city_id: $("#form_city_id").val(), 
			   sport_id: $("#form_sport_id").val(),
			   city: $("#form_city").val(), 
			   sport: $("#form_sport").val() 
		   }, function(){
			   $('html,body').animate({scrollTop: $("#search_results").offset().top},'slow');
		   });
		}
    });
    
	
	
	
	  $( "#city_label" ).position({
          my: "left bottom",
		  at: "left top",
		  of: "#form_city",
		  collision: "none"
      });
	  $( "#sport_label" ).position({
          my: "left bottom",
		  at: "left top",
		  of: "#form_sport",
		  collision: "none"
      });

	
	          
 
});


    $('img').load(function() {
        $(this).show(); //muestra el div despues de que la imagen carga.
    });
</script>