<div class="home">
    <div class="slider_home"><div class="squadrapp_canvas">
        <div class="contenido_slider">
            <h1>Nunca fue tan f&aacute;cil ponerse de acuerdo</h1>
            <h2>Encuentra la cancha de f&uacute;tbol y convoca a tus amigos para jugar</h2>
            <h3>Pronto sabr&aacute;s como!</h3>
            <div class="email_form1">
                <div class="fields" align="right">
                    <form method="post" id="email_player_form" action="javascript:void();">
                            <input type="text" name="email" id="email" class="field1" placeholder="Ingresa tu e-mail y te notificaremos" />
                            <a href="javascript:void(0);" id="validaEmail" class="inscribete_178x60"></a>
                    </form>
                </div>
            <div class="back"></div>
            </div>
        </div>
    </div> 
    <div class="bg"></div>
    </div>
    
    <div class="icons"><div class="squadrapp_canvas">
    	<div class="icon">
        	<img src="<?php echo $this->baseUrl("/images/home/reserva.png"); ?>" />
            <p>Reserva canchas en tu ciudad</p>
            <div class="number1"></div>
        </div>
        <div class="icon">
        	<img src="<?php echo $this->baseUrl("/images/home/convoca.png"); ?>" />
            <p>Convoca a tus amigos</p>
            <div class="number2"></div>
        </div>
        <div class="icon">
        	<img src="<?php echo $this->baseUrl("/images/home/confirma.png"); ?>" />
            <p>Confirma tu asistencia</p>
            <div class="number3"></div>
        </div>
        <div class="corte"></div>
    </div></div>
    
   <div class="squadrapp_canvas" align="center">
   	   <div align="center"><h2>&Uacute;nete a partidos disponibles de tus amigos y completa el equipo!</h2></div>
       <div class="contenido_slider2">
            <ul class="bxslider">
                  <li><div align="center">
                        <div class="twocolumns">
                            <div style="width:310px; margin:150px 60px 0 0;">
                            	<p style="font-size:24px; line-height:28px; color:#555555; font-weight:lighter; margin-bottom: 60px; text-align:left;">
                                Espera muy pronto la mejor aplicación web y móvil para reservar canchas, convocar jugadores y conectarte con tus amigos.
                                </p>  
                                <p style="font-size:20px; color:#555555; text-align: left; margin-bottom: 10px;">
                                	<strong>S&iacute;guenos en</strong>
                                </p>                          	
                                <p style="text-align: left;">
                                    <a href="https://twitter.com/squadrapp" target="_blank" class="btn_twitter"></a>
                                    <a href="http://www.facebook.com/SquadrApp" target="_blank" class="btn_facebook"></a>
                                </p>
                            </div>
                        </div>
                        <div class="twocolumns_slider"><img src="<?php echo $this->baseUrl("/images/home/iphone_app.png"); ?>" /></div>
                        <div class="corte"></div>
                  </div></li>
            </ul>
        <div class="squadrapp_canvas slider1" align="center"></div>
        </div>
    </div>    
</div>



<script>
    
    $(document).ready(function(){
        
        
        
        $("#validaEmail").click(function() {
            patCorreo = /^(.+\@.+\..+)$/;
	    if (patCorreo.test($.trim($("#email").val()))){
			$.colorbox({html:'<div style="width:500px; height:500px; vertical-align:middle; text-align:center; background:url(<?php echo $this->baseUrl("/img/background.png"); ?>) repeat;"><div style="padding-top:218px; text-align:center;"><img src="<?php echo $this->baseUrl("/img/loader.gif"); ?>" width:"64px" /></div></div>', width:"500px", height:"500px", scrolling:false});
                $.ajax({
                    type: "POST",
                    url: '/site/site/registro-email',
                    data: $("#email_player_form").serialize(), // serializes the form's elements.
                    success: function(data)
                   {
                       if (data == 'ok'){
                            $.colorbox({html:'<div style="width:500px; height:500px; vertical-align:middle; text-align:center; background:url(<?php echo $this->baseUrl("/img/background.png"); ?>) repeat;"><div style="padding:150px 80px 0 80px; text-align:left; color:#333;"><p style="font-size:40px; color:#333; font-weight:bold; margin-bottom:20px;">Gracias!</p><p style="font-size:20px; line-height:22px; color:#333; font-weight:lighter; margin-bottom:20px;">Te notificaremos para que hagas parte de la versi&oacute;n Beta</p><p style="font-size:20px; line-height:22px; color:#333; font-weight:bold;">!Bienvenido a la comunidad SquadrApp!</p></div></div>', width:"500px", height:"500px", scrolling:false});
                       }else {
                       
                       }
                   }
               }); 
            }
          });
          
          
          
        
    });
    
   
</script>