<div id="home" align="center">
	<div class="botones">
    	<div class="btn1"><a href="#" onclick="loginUsingOAUTH('http://squadrapp.com/user/user/login-facebook-mobile');"><img src="/img/movil/btn_facebook.png" /></a></div>
        <div class="btn2"><a href="mobile-registro-cancha" onclick=""><img src="/img/movil/btn_cancha_354x72.png" /></a></div>
    </div>
    
    <div class="goIn">
    	<a href="#" onclick="loginUsingOAUTH('http://squadrapp.com/user/user/login-facebook-mobile');">¿Ya tienes una cuenta? <span class="titulo">Entra ahora</span></a>
    </div>
</div>



<style>
	#home{
		width:390px;
		margin:0 auto;
		background:url(/img/movil/bg_home.jpg) center top no-repeat;
		padding:360px 0 0 0;
	}
	#home .botones{
		margin:10px;
		background:#f8f8f8;
		border:#CCC 1px solid;
		box-shadow: 0px 0px 2px #000;
   		-webkit-box-shadow: 0px 0px 2px #000;
   		-moz-box-shadow: 0px 0px 2px #000;
	}
	#home .botones .btn1{
		padding:5px;
		border-bottom:#CCC 1px solid;
	}
	#home .botones .btn2{
		padding:5px;
	}
	#home .goIn{
		margin:60px 0 40px 0;
		text-align:center;
		font-size:18px;
		color:#999;
	}
	#home .goIn .titulo{
		font-weight:bold;
		font-size:24px;
	}
</style>