<div class="slide_registro"><div class="squadrapp_canvas"><div class="container1">

    	<div class="twocolumns">
            <div class="content_squadrapp">
                <p>Si eres un centro deportivo</p>
                    <h1>Haz que millones de jugadores encuentren tu Cancha de fútbol disponible para jugar</h1>
                <h5>Regístrate ingresando tus datos y te contactaremos para hacer visibles tus canchas</h5>
            </div>
        </div>
        <div class="twocolumns">
            <div class="content_squadrapp">
                <div class="form" align="center">
                    <div class="error" id="error-registro" align="left"></div>
                    <form method="post" name="canchas" id="canchas_form" action="javascript:void();">
                        <div class="field">
                            <input type="text" name="cancha" id="cancha" class="field1" placeholder="Nombre del establecimiento">
                        </div>
                        <div class="field">
                            <input type="text" name="email" id="email" class="field1" placeholder="Correo electrónico">
                        </div>
                        <div class="field">
                            <input type="text" name="direccion" id="direccion" class="field1" placeholder="Dirección">
                        </div>
                        <div class="field">
                            <input type="text" name="telefono" id="telefono" class="field2" placeholder="Teléfono">
                        <strong>&nbsp;</strong>
                            <input type="text" name="celular" id="celular" class="field2" placeholder="Celular">
                        </div>
                        <div class="field">
                            <input type="text" name="encargado" id="encargado" class="field1" placeholder="Nombre de persona encargada">
                        </div>
                        <div class="button" align="center">
                        	<a href="javascript:void(0);" id="validaCancha" class="registrate_381x69" onClick="_gaq.push (['_trackEvent' ,'CentroDeportivo' ,'clicRegistrar' ,'Guardar_dormulario']);" ></a>
                        </div>
                    </form>
                    <div class="bg2"></div>
                </div>
            </div>
        </div>
        <div class="corte"></div>
    



</div></div></div>


<div class="squadrapp_canvas" align="center"><div class="container2">
    	<div class="icon">
        	<img src="<?php echo $this->baseUrl("/img/icons/reserva.png"); ?>" />
            <p>Eleva el nivel de ocupaci&oacute;n de tus canchas</p>
        </div>
        <div class="icon">
        	<img src="<?php echo $this->baseUrl("/img/icons/fotos.png"); ?>" />
            <p>Adquiere visibilidad de tu centro deportivo</p>
        </div>
        <div class="icon">
        	<img src="<?php echo $this->baseUrl("/img/icons/usuarios.png"); ?>" />
            <p>Accede a más clientes</p>
        </div>
        <div class="corte"></div>
<div class="bg"></div>
</div></div>  


<style>



#squadrapp .icons{
	background:#FFF;
	margin:0;
	padding:10px 0;
	vertical-align:top;
	text-align:center;
	box-shadow: 0 4px 10px 1px #888;
   -webkit-box-shadow: 0 4px 10px 1px #888;
   -moz-box-shadow: 0 4px 10px 1px #888;
   z-index: 101;
}
#squadrapp .icon{
	width:310px;
	text-align:center;
	vertical-align:top;
	display:block;
	float:left;
	margin:40px 0;
}
#squadrapp .icon p{
	font-size:22px;
	line-height:26px;
	font-weight:lighter;
	margin:10px 55px 0 55px;
	color:#333;
}

.slide_registro{
	background:#000 url(/img/banner_registro.jpg) center top no-repeat;
	height:560px;
}




.content_squadrapp{
	padding:0 20px;
	text-align:left;
	vertical-align:middle;
	color:#FFF;
}
.content_squadrapp .form{
	padding:20px;
}
.content_squadrapp .form input{
	font-size:20px;
	color:#333;
}
.content_squadrapp .form .field {
	padding:5px 0;
}
	
.content_squadrapp .form .field1{
	width:360px;
	padding:10px;
	margin:0;
}
.content_squadrapp .form .field2{
	width:175px;
	padding:10px;
	margin:0;
	margin:0;
}
.content_squadrapp .form .button{
	padding:10px 0 0 0;
}
.content_squadrapp .form p{
	color:#FFF;
	font-size:14px; 
	margin:10px 0 0 0;
	padding:0;
}
.content_squadrapp .bg2 {
	background:#333;
	text-align:center;
	vertical-align:middle;
	filter:alpha(opacity=30); 
	-moz-opacity:0.3; 
	-khtml-opacity: 0.3;	
	opacity: 0.3;
	position:absolute;
	top:0;
	right:0;
	left:0;
	bottom:0;
	z-index:-1;
	padding:10px 0;
	/*para Firefox*/
	-moz-border-radius: 7px 7px 7px 7px;
	/*para Safari y Chrome*/
	-webkit-border-radius: 7px 7px 7px 7px;
	/* para Opera */
	border-radius: 7px 7px 7px 7px;
	/* para IE */
	/*behavior:url(/css/border.htc);*/
	box-shadow:0 1px 5px 2px #000;
   -webkit-box-shadow:0 1px 5px 2px #000;
   -moz-box-shadow:0 1px 5px 2px #000;
}
.content_squadrapp p{
	color:#fff;
	font-size:18px;
	font-weight:lighter;
	margin:20px 0 30px 0;
}
.content_squadrapp h1{
	color:#ffffff;
	font-size:43px;
	line-height: 43px;
	font-weight:lighter;
	margin-bottom:30px;
}
.content_squadrapp h5{	
	font-weight:lighter;
	font-size:18px;
}

.twocolumns{
	float:left;
	width:465px;
}

.container1{
	padding:120px 0 20px 0;
	margin:0;
}

.container2{
	margin-bottom:30px;
}




a.registrate_364x53{
	display: block;
	width: 364px;
	height: 53px;
	text-decoration: none;
	background: url(/img/btn/registrate_364x53.png);
}
a.registrate_364x53:hover {
	background-position: -364px 0;
	}



</style>


<script>
    
    $(document).ready(function(){
        
        
        
        $("#validaCancha").click(function() {
            patCorreo = /^(.+\@.+\..+)$/;
	    if ($.trim($("#cancha").val()) == '') {
                $("#error-registro").html('Ingrese nombre');
	    }else if ($.trim($("#email").val()) == '') {
                $("#error-registro").html('Ingrese correo');
            }else if (!patCorreo.test($.trim($("#email").val()))){
                $("#error-registro").html('Correo invalido');
            }else {
                $.colorbox({html:'<div style="width:500px; height:500px; vertical-align:middle; text-align:center; background:url(<?php echo $this->baseUrl("/img/background.png"); ?>) repeat;"><div style="padding-top:218px; text-align:center;"><img src="<?php echo $this->baseUrl("/img/loader.gif"); ?>" width:"64px" /></div></div>', width:"500px", height:"500px", scrolling:false});
                $.ajax({
                    type: "POST",
                    url: '/site/site/nueva-cancha',
                    data: $("#canchas_form").serialize(), // serializes the form's elements.
                    success: function(data)
                   {
                       if (data == 'ok'){
                          $.colorbox({html:'<div style="width:500px; height:500px; vertical-align:middle; text-align:center; background:url(<?php echo $this->baseUrl("/img/background.png"); ?>) repeat;"><div style="padding:150px 80px 0 80px; text-align:left; color:#333;"><p style="font-size:40px; color:#333; font-weight:bold; margin-bottom:20px;">Gracias!</p><p style="font-size:20px; line-height:22px; color:#333; font-weight:lighter; margin-bottom:20px;">Te notificaremos para que hagas parte de la versi&oacute;n Beta</p><p style="font-size:20px; line-height:22px; color:#333; font-weight:bold;">!Bienvenido a la comunidad SquadrApp!</p></div></div>', width:"500px", height:"500px", scrolling:false});
                       }else {
						   
                        }
                   }
               });
            }	 
            
          });
          
          
          
        
    });
    
   
</script>